[package]
name = "solver-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6"
good_lp = { version = "1", default-features = false, features = ["highs"] }
num = "0.4"
itertools = "0.14"
lasso = "0.7"
petgraph = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
stacker = "0.1"
