[package]
name = "solver-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6"
good_lp = { version = "1", default-features = false, features = ["highs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
